name: Merge into bsts
on:
  push:
    branches:
      - 'main'
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge bsts...main
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          target_branch: bsts